import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import threading

def send_alert_email(threat):
    """
    Sends an email alert for a detected threat.
    This function is designed to be run in a separate thread to not block the main request.
    """
    
    sender_email = os.getenv('EMAIL_USER')
    sender_password = os.getenv('EMAIL_PASS')
    receiver_email = os.getenv('EMAIL_RECEIVER')

    if not sender_email or not sender_password or not receiver_email:
        print("Email configuration missing. Skipping alert.")
        return

    subject = f"SECURITY ALERT: {threat.get('scenario', {}).get('type', 'Unknown Threat')} Detected"
    
    # HTML Body
    html_content = f"""
    <html>
        <head>
            <style>
                .container {{ font-family: Arial, sans-serif; padding: 20px; background-color: #f8fafc; }}
                .card {{ background-color: white; padding: 20px; border-radius: 8px; border: 1px solid #e2e8f0; }}
                .header {{ color: #dc2626; font-size: 24px; font-weight: bold; margin-bottom: 20px; }}
                .row {{ margin-bottom: 10px; }}
                .label {{ font-weight: bold; color: #64748b; }}
                .value {{ color: #1e293b; }}
                .badge {{ background-color: #fee2e2; color: #991b1b; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="card">
                    <div class="header">⚠️ Security Threat Detected</div>
                    
                    <div class="row">
                        <span class="label">Threat Type:</span>
                        <div class="value" style="font-size: 18px; font-weight: bold; margin-top: 5px;">
                            {threat.get('scenario', {}).get('type')}
                        </div>
                    </div>

                    <div class="row">
                        <span class="label">Severity Level:</span>
                        <span class="badge">{threat.get('risk_level')}</span>
                    </div>

                    <div class="row">
                        <span class="label">Risk Score:</span>
                        <span class="value">{threat.get('risk_score')}/100</span>
                    </div>

                    <div class="row">
                        <span class="label">Time Detected:</span>
                        <div class="value">{threat.get('timestamp')}</div>
                    </div>

                    <div class="row">
                        <span class="label">Description:</span>
                        <div class="value">{threat.get('scenario', {}).get('description')}</div>
                    </div>
                     
                    <div style="margin-top: 20px; border-top: 1px solid #e2e8f0; padding-top: 15px;">
                        <span class="label">Recommended Actions:</span>
                        <ul style="color: #334155;">
                            {''.join([f'<li>{rec}</li>' for rec in threat.get('recommendations', [])])}
                        </ul>
                    </div>
                </div>
                <div style="text-align: center; margin-top: 20px; color: #94a3b8; font-size: 12px;">
                    Generated by AI-Powered Threat Detection System
                </div>
            </div>
        </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = subject
    msg.attach(MIMEText(html_content, 'html'))

    try:
        # Connect to Gmail's SMTP server
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        print(f"Alert email sent successfully to {receiver_email}")
    except Exception as e:
        print(f"Failed to send email alert: {str(e)}")

def trigger_email_alert(threat):
    """Wrapper to run email sending in background thread"""
    email_thread = threading.Thread(target=send_alert_email, args=(threat,))
    email_thread.daemon = True
    email_thread.start()
