import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Helper to get colors based on risk level
const getLevelColor = (level) => {
    switch (level?.toUpperCase()) {
        case 'CRITICAL': return [220, 38, 38]; // Red
        case 'HIGH': return [239, 68, 68]; // Light Red
        case 'MEDIUM': return [234, 179, 8]; // Yellow
        case 'LOW': return [34, 197, 94]; // Green
        default: return [148, 163, 184]; // Grey
    }
};

export const generateGlobalReport = (threats) => {
    const doc = new jsPDF();

    // --- Branding & Header ---
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text("Security Threat Audit", 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);
    doc.text("System Wide Analysis", 196, 20, { align: 'right' });

    // --- Stats ---
    const total = threats.length;
    const critical = threats.filter(t => t.risk_level === 'CRITICAL').length;

    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("Executive Summary", 14, 50);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Events: ${total} | Critical: ${critical}`, 14, 58);

    const tableData = threats.map(t => [
        new Date(t.timestamp).toLocaleString(),
        t.risk_level,
        t.scenario?.type || 'Unknown',
        `${t.risk_score}/100`,
        `${t.confidence}%`
    ]);

    autoTable(doc, {
        startY: 65,
        head: [['Timestamp', 'Level', 'Type', 'Score', 'Conf.']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [15, 23, 42] },
        didParseCell: function (data) {
            if (data.section === 'body' && data.column.index === 1) {
                data.cell.styles.textColor = getLevelColor(data.cell.raw);
            }
        }
    });

    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: 'right' });
    }
    doc.save('global-threat-report.pdf');
};

export const generateSingleThreatReport = (threat) => {
    const doc = new jsPDF();
    const primaryBlue = [15, 23, 42]; // #0f172a
    const accentColor = getLevelColor(threat.risk_level);

    // ================= PAGE 1: COVER SHEET =================

    // Background Pattern (Subtle strip on left)
    doc.setFillColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.rect(0, 0, 210, 297, 'F'); // Full dark background for cover

    // Decorative geometric shapes
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(0.5);
    doc.line(20, 20, 190, 20);
    doc.line(20, 277, 190, 277);

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(32);
    doc.setFont('helvetica', 'bold');
    doc.text("SECURITY INCIDENT", 105, 100, { align: 'center' });
    doc.text("DETAILED REPORT", 105, 115, { align: 'center' });

    // Badge
    doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.roundedRect(85, 130, 40, 12, 6, 6, 'F');
    doc.setFontSize(10);
    doc.text(threat.risk_level, 105, 137, { align: 'center' });

    // Meta Info
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(203, 213, 225); // Slate-300
    doc.text(`Incident ID: ${threat.id || 'N/A'}`, 105, 160, { align: 'center' });
    doc.text(`Detected: ${new Date(threat.timestamp).toLocaleString()}`, 105, 168, { align: 'center' });

    // Bottom Branding
    doc.setFontSize(10);
    doc.text("Generated by CyberGuard AI", 105, 260, { align: 'center' });

    // ================= PAGE 2: EXECUTIVE SUMMARY =================
    doc.addPage();

    // Header
    doc.setFillColor(241, 245, 249); // Slate-100 header
    doc.rect(0, 0, 210, 30, 'F');
    doc.setFontSize(14);
    doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.setFont('helvetica', 'bold');
    doc.text("Executive Analysis", 14, 20);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(threat.scenario?.type || "Unknown Threat Type", 196, 20, { align: 'right' });

    let y = 45;

    // Overview Section
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Incident Overview", 14, y);
    y += 8;

    // Description Box
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(14, y, 182, 35, 2, 2, 'S'); // Outline only

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    const descLines = doc.splitTextToSize(threat.scenario?.description || "No description provided.", 170);
    doc.text(descLines, 20, y + 10);

    y += 50;

    // Visual Metrics (Side by Side)
    // Risk Score
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.text("Risk Assessment", 14, y);

    y += 15;

    // Draw Risk Bar
    doc.setFontSize(10);
    doc.text("Risk Score", 14, y);
    doc.setFillColor(226, 232, 240); // Grey track
    doc.roundedRect(40, y - 4, 100, 4, 2, 2, 'F');
    doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]); // Colored progress
    doc.roundedRect(40, y - 4, threat.risk_score, 4, 2, 2, 'F'); // Width = score
    doc.text(`${threat.risk_score}/100`, 150, y);

    y += 15;

    // Draw Confidence Bar
    doc.text("AI Confidence", 14, y);
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(40, y - 4, 100, 4, 2, 2, 'F');
    doc.setFillColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]); // Blue progress for confidence
    doc.roundedRect(40, y - 4, threat.confidence, 4, 2, 2, 'F');
    doc.text(`${threat.confidence}%`, 150, y);

    y += 30;

    // Technical Details Table
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Technical Indicators", 14, y);
    y += 5;

    const riskFactors = threat.risk_factors || {};
    const techData = Object.entries(riskFactors).map(([k, v]) => [
        k.replace(/_/g, ' ').toUpperCase(),
        v >= 4 ? 'High' : v >= 2 ? 'Medium' : 'Low',
        `${v}/5`
    ]);

    if (techData.length > 0) {
        autoTable(doc, {
            startY: y,
            head: [['Indicator', 'Severity Class', 'Score']],
            body: techData,
            theme: 'grid',
            headStyles: { fillColor: primaryBlue },
            styles: { fontSize: 10, cellPadding: 4 },
            columnStyles: { 0: { fontStyle: 'bold' } }
        });
        y = doc.lastAutoTable.finalY + 20;
    } else {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'italic');
        doc.text("No specific risk factors identified.", 14, y + 10);
        y += 20;
    }

    // ================= PAGE 3: REMEDIATION =================
    doc.addPage();

    // Header
    doc.setFillColor(241, 245, 249);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setFontSize(14);
    doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.setFont('helvetica', 'bold');
    doc.text("Remediation Strategy", 14, 20);

    y = 45;

    doc.setFontSize(12);
    doc.text("Recommended Actions", 14, y);
    y += 10;

    const recs = threat.recommendations || [];
    recs.forEach((rec, index) => {
        // Draw Card for each recommendation
        doc.setDrawColor(226, 232, 240);
        doc.setFillColor(255, 255, 255);

        // Dynamic height based on text
        const recLines = doc.splitTextToSize(rec, 170);
        const cardHeight = (recLines.length * 5) + 15;

        doc.roundedRect(14, y, 182, cardHeight, 2, 2, 'FD'); // Fill and Draw

        // Bullet Icon
        doc.setFillColor(34, 197, 94); // Green
        doc.circle(24, y + 8, 3, 'F');

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(51, 65, 85);
        doc.text(recLines, 32, y + 9);

        y += cardHeight + 5;
    });

    // Footer on all layout pages
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        if (i === 1) continue; // Skip cover

        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate-400
        doc.line(14, 280, 196, 280); // Divider line
        doc.text(`Confidential Analysis - ${threat.id}`, 14, 288);
        doc.text(`Page ${i} of ${pageCount}`, 196, 288, { align: 'right' });
    }

    doc.save(`incident-report-${threat.id ? threat.id.slice(0, 8) : 'export'}.pdf`);
};
